decoration {
    rounding = 12
    
    blur {
        enabled = true
        size = 12
        passes = 3
        new_optimizations = true
        xray = false
        noise = 0.02
        contrast = 1.1
        brightness = 1.2
        vibrancy = 0.3
    }

    drop_shadow = yes
    shadow_range = 20
    shadow_render_power = 3
    col.shadow = rgba(00000044)
}
