from __future__ import annotations
import logging, os, subprocess
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

MAX_ITERATIONS = 10

class ProjectBuilder:
    def __init__(self, prax_dir: Path | None = None):
        self.prax_dir = prax_dir or Path(os.getenv("PRAX_DATA_DIR", "/var/prax"))
    
    def scaffold(self, proposal: Any) -> Path:
        project_name = self._slugify(proposal.title if hasattr(proposal, 'title') else "project")
        project_path = self.prax_dir / "projects" / project_name
        project_path.mkdir(parents=True, exist_ok=True)
        (project_path / "src").mkdir(exist_ok=True)
        (project_path / "tests").mkdir(exist_ok=True)
        (project_path / "README.md").write_text(f"# {project_name}\n\n{proposal.problem_statement if hasattr(proposal, 'problem_statement') else ''}")
        (project_path / "requirements.txt").write_text("fastapi>=0.111.0\nuvicorn[standard]>=0.29.0\n")
        (project_path / "Dockerfile").write_text("FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nCMD [\"uvicorn\", \"src.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n")
        (project_path / "src" / "__init__.py").write_text("")
        (project_path / "src" / "main.py").write_text('"""Auto-generated by Prax."""\nfrom fastapi import FastAPI\n\napp = FastAPI(title="' + project_name + '")\n\n@app.get("/health")\nasync def health():\n    return {"status": "ok"}\n')
        (project_path / "tests" / "__init__.py").write_text("")
        (project_path / "tests" / "test_main.py").write_text("from httpx import ASGITransport, AsyncClient\n\nasync def test_health():\n    from src.main import app\n    transport = ASGITransport(app=app)\n    async with AsyncClient(transport=transport, base_url=\"http://test\") as ac:\n        resp = await ac.get(\"/health\")\n        assert resp.status_code == 200\n")
        return project_path
    
    def build(self, project_path: Path) -> bool:
        result = subprocess.run(
            ["python", "-m", "pytest", str(project_path / "tests"), "-q"],
            capture_output=True, text=True,
        )
        return result.returncode == 0
    
    def iterate_until_green(self, project_path: Path) -> bool:
        for i in range(MAX_ITERATIONS):
            if self.build(project_path):
                logger.info("Project %s passed tests on iteration %d", project_path.name, i)
                return True
            logger.info("Project %s iteration %d failed, retrying", project_path.name, i)
        return False
    
    @staticmethod
    def _slugify(name: str) -> str:
        import re
        return re.sub(r'[^a-z0-9-]', '', name.lower().replace(' ', '-'))[:64] or "project"
