#!/bin/sh
set -e

LB_DISTRIBUTION="bookworm"
LB_ARCHITECTURE="amd64"
LB_BINARY_IMAGES="iso-hybrid"
LB_DEBIAN_INSTALLER="live"
LB_BOOTLOADER_BIOS="syslinux"
LB_BOOTLOADER_EFI="grub-efi"

lb config noauto \
  --mode debian \
  --architecture amd64 \
  --distribution bookworm \
  --debian-installer none \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet splash" \
  --linux-flavours amd64 \
  --memtest none \
  --iso-application "PradyOS" \
  --iso-preparer "PradyOS Project" \
  --iso-publisher "PradyOS" \
  --iso-volume "PRADY_OS_1_0" \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap "http://deb.debian.org/debian/" \
  --mirror-chroot "http://deb.debian.org/debian/" \
  --mirror-binary "http://deb.debian.org/debian/" \
--mirror-bootstrap-security "http://security.debian.org/debian-security" \
--mirror-chroot-security "http://security.debian.org/debian-security" \
--mirror-binary-security "http://security.debian.org/debian-security" \
  "${@}"
